#!/usr/bin/env python3
# Generates nextguard-<locale>.mo for the 9 supported languages from the strings
# below. Run: python3 build-mo.py   (no external deps — writes .mo binary directly)
import os, struct

LOCALES = ["es_ES", "pt_BR", "fr_FR", "de_DE", "nl_NL", "ja", "zh_CN", "hi_IN"]
IDX = {"es_ES": 0, "pt_BR": 1, "fr_FR": 2, "de_DE": 3, "nl_NL": 4, "ja": 5, "zh_CN": 6, "hi_IN": 7}

# msgid -> [es, pt, fr, de, nl, ja, zh, hi]
T = {
 "NextGuard": ["NextGuard","NextGuard","NextGuard","NextGuard","NextGuard","NextGuard","NextGuard","NextGuard"],
 "NextGuard Security": ["NextGuard Security","NextGuard Security","NextGuard Security","NextGuard Security","NextGuard Security","NextGuard Security","NextGuard 安全","NextGuard सुरक्षा"],
 "Scan now": ["Escanear ahora","Escanear agora","Scanner maintenant","Jetzt scannen","Nu scannen","今すぐスキャン","立即扫描","अभी स्कैन करें"],
 "Connect & scan": ["Conectar y escanear","Conectar e escanear","Connecter et scanner","Verbinden & scannen","Verbinden & scannen","接続してスキャン","连接并扫描","कनेक्ट करें और स्कैन करें"],
 "Connect &amp; scan": ["Conectar y escanear","Conectar e escanear","Connecter et scanner","Verbinden & scannen","Verbinden & scannen","接続してスキャン","连接并扫描","कनेक्ट करें और स्कैन करें"],
 "Connect": ["Conectar","Conectar","Connecter","Verbinden","Verbinden","接続","连接","कनेक्ट करें"],
 "API Key": ["API Key","API Key","Clé API","API-Key","API-sleutel","APIキー","API 密钥","API Key"],
 "Status": ["Estado","Status","Statut","Status","Status","ステータス","状态","स्थिति"],
 "Manual Sync": ["Sincronización manual","Sincronização manual","Synchronisation manuelle","Manuelle Synchronisierung","Handmatige sync","手動同期","手动同步","मैनुअल सिंक"],
 "Sync Now": ["Sincronizar ahora","Sincronizar agora","Synchroniser","Jetzt synchronisieren","Nu synchroniseren","今すぐ同期","立即同步","अभी सिंक करें"],
 "Connected": ["Conectado","Conectado","Connecté","Verbunden","Verbonden","接続済み","已连接","कनेक्ट हो गया"],
 "Severity": ["Severidad","Severidade","Sévérité","Schweregrad","Ernst","深刻度","严重程度","गंभीरता"],
 "Component": ["Componente","Componente","Composant","Komponente","Component","コンポーネント","组件","घटक"],
 "Installed": ["Instalada","Instalada","Installée","Installiert","Geïnstalleerd","インストール済み","已安装","इंस्टॉल"],
 "Vulnerability": ["Vulnerabilidad","Vulnerabilidade","Vulnérabilité","Schwachstelle","Kwetsbaarheid","脆弱性","漏洞","कमज़ोरी"],
 "Fixed in": ["Corregido en","Corrigido em","Corrigé dans","Behoben in","Opgelost in","修正バージョン","修复于","ठीक किया गया"],
 "Expires in": ["Expira en","Expira em","Expire dans","Läuft ab in","Verloopt over","有効期限","有效期","समाप्त होगा"],
 "minutes": ["minutos","minutos","minutes","Minuten","minuten","分","分钟","मिनट"],
 "Free scan active — no account needed": ["Escaneo gratis activo — sin cuenta","Verificação grátis ativa — sem conta","Scan gratuit actif — sans compte","Kostenloser Scan aktiv — kein Konto nötig","Gratis scan actief — geen account nodig","無料スキャン有効 — アカウント不要","免费扫描已激活 — 无需账户","मुफ़्त स्कैन सक्रिय — खाते की ज़रूरत नहीं"],
 "Vulnerabilities detected on your site": ["Vulnerabilidades detectadas en tu sitio","Vulnerabilidades detectadas no seu site","Vulnérabilités détectées sur votre site","Auf deiner Seite erkannte Schwachstellen","Kwetsbaarheden op je site","あなたのサイトで検出された脆弱性","在你的网站检测到的漏洞","आपकी साइट पर पाई गई कमज़ोरियाँ"],
 "%d vulnerabilities found": ["%d vulnerabilidades encontradas","%d vulnerabilidades encontradas","%d vulnérabilités trouvées","%d Schwachstellen gefunden","%d kwetsbaarheden gevonden","%d 件の脆弱性を検出","发现 %d 个漏洞","%d कमज़ोरियाँ मिलीं"],
 "+%d more vulnerabilities hidden — register free to see the full report.": ["+%d vulnerabilidades ocultas — registrate gratis para ver el informe completo.","+%d vulnerabilidades ocultas — registre-se grátis para ver o relatório completo.","+%d vulnérabilités masquées — inscrivez-vous gratuitement pour le rapport complet.","+%d weitere Schwachstellen verborgen — kostenlos registrieren für den vollen Bericht.","+%d kwetsbaarheden verborgen — registreer gratis voor het volledige rapport.","他 +%d 件は非表示 — 無料登録で全レポートを表示。","还有 +%d 个漏洞被隐藏 — 免费注册查看完整报告。","+%d और कमज़ोरियाँ छिपी हैं — पूरी रिपोर्ट के लिए मुफ़्त रजिस्टर करें।"],
 "Register free for the full report + continuous monitoring": ["Registrate gratis para el informe completo + monitoreo continuo","Registre-se grátis para o relatório completo + monitoramento contínuo","Inscrivez-vous gratuitement pour le rapport complet + surveillance continue","Kostenlos registrieren für den vollen Bericht + laufende Überwachung","Registreer gratis voor het volledige rapport + doorlopende monitoring","無料登録で全レポート＋継続モニタリング","免费注册获取完整报告 + 持续监控","पूरी रिपोर्ट + निरंतर निगरानी के लिए मुफ़्त रजिस्टर करें"],
 "No known vulnerabilities found on your site.": ["No encontramos vulnerabilidades conocidas en tu sitio.","Nenhuma vulnerabilidade conhecida encontrada no seu site.","Aucune vulnérabilité connue trouvée sur votre site.","Keine bekannten Schwachstellen auf deiner Seite gefunden.","Geen bekende kwetsbaarheden op je site gevonden.","あなたのサイトに既知の脆弱性は見つかりませんでした。","在你的网站未发现已知漏洞。","आपकी साइट पर कोई ज्ञात कमज़ोरी नहीं मिली।"],
 "This free key has %d scan(s) left and expires in 2 hours. When it runs out, generate a new free key on the home page or register for unlimited continuous monitoring.": ["Esta key gratis tiene %d escaneo(s) restantes y expira en 2 horas. Cuando se agote, generá una nueva key gratis en la página principal o registrate para monitoreo continuo ilimitado.","Esta chave grátis tem %d verificação(ões) restante(s) e expira em 2 horas. Quando acabar, gere uma nova chave grátis na página inicial ou registre-se para monitoramento contínuo ilimitado.","Cette clé gratuite a %d scan(s) restant(s) et expire dans 2 heures. Une fois épuisée, générez une nouvelle clé gratuite sur la page d'accueil ou inscrivez-vous pour une surveillance continue illimitée.","Dieser kostenlose Key hat noch %d Scan(s) und läuft in 2 Stunden ab. Danach erzeuge einen neuen kostenlosen Key auf der Startseite oder registriere dich für unbegrenzte Überwachung.","Deze gratis sleutel heeft nog %d scan(s) en verloopt over 2 uur. Genereer daarna een nieuwe gratis sleutel op de homepage of registreer voor onbeperkte monitoring.","この無料キーは残り %d 回、2時間で期限切れです。なくなったらホームで新しい無料キーを生成するか、無制限の継続モニタリングに登録してください。","此免费密钥还剩 %d 次扫描，2 小时后过期。用完后请在首页生成新的免费密钥，或注册以获得无限持续监控。","इस मुफ़्त key में %d स्कैन बचे हैं और 2 घंटे में समाप्त हो जाएगी। समाप्त होने पर होम पेज पर नई मुफ़्त key बनाएं या असीमित निगरानी के लिए रजिस्टर करें।"],
 "Free scan active (no account). Register at NextGuard for continuous monitoring + alerts.": ["Escaneo gratis activo (sin cuenta). Registrate en NextGuard para monitoreo continuo + alertas.","Verificação grátis ativa (sem conta). Registre-se no NextGuard para monitoramento contínuo + alertas.","Scan gratuit actif (sans compte). Inscrivez-vous sur NextGuard pour surveillance continue + alertes.","Kostenloser Scan aktiv (kein Konto). Registriere dich bei NextGuard für laufende Überwachung + Alerts.","Gratis scan actief (geen account). Registreer bij NextGuard voor doorlopende monitoring + alerts.","無料スキャン有効（アカウントなし）。継続モニタリング＋アラートはNextGuardに登録。","免费扫描已激活（无账户）。在 NextGuard 注册以获得持续监控 + 警报。","मुफ़्त स्कैन सक्रिय (बिना खाते)। निरंतर निगरानी + अलर्ट के लिए NextGuard पर रजिस्टर करें।"],
 "Not configured. Connect above to get started.": ["Sin configurar. Conectá arriba para empezar.","Não configurado. Conecte acima para começar.","Non configuré. Connectez-vous ci-dessus pour commencer.","Nicht konfiguriert. Verbinde oben, um zu starten.","Niet geconfigureerd. Verbind hierboven om te beginnen.","未設定です。上で接続して開始してください。","未配置。请在上方连接以开始。","कॉन्फ़िगर नहीं है। शुरू करने के लिए ऊपर कनेक्ट करें।"],
 "Connected via device token. Sync runs daily automatically.": ["Conectado vía device token. La sincronización corre a diario automáticamente.","Conectado via device token. A sincronização roda diariamente.","Connecté via device token. La synchronisation s'exécute chaque jour.","Über Device-Token verbunden. Sync läuft täglich automatisch.","Verbonden via device token. Sync draait dagelijks automatisch.","デバイストークンで接続済み。同期は毎日自動実行。","已通过设备令牌连接。每天自动同步。","डिवाइस टोकन से कनेक्ट। सिंक रोज़ अपने आप चलता है।"],
 "Legacy configuration — reconnect using the Device Auth Flow above.": ["Configuración antigua — reconectá con el Device Auth Flow de arriba.","Configuração antiga — reconecte com o Device Auth Flow acima.","Configuration héritée — reconnectez via le Device Auth Flow ci-dessus.","Alte Konfiguration — über den Device-Auth-Flow oben neu verbinden.","Verouderde configuratie — verbind opnieuw via de Device Auth Flow hierboven.","旧設定 — 上のデバイス認証フローで再接続してください。","旧配置 — 请使用上方的设备授权流程重新连接。","पुराना कॉन्फ़िगरेशन — ऊपर Device Auth Flow से फिर से कनेक्ट करें।"],
 "Connect a different project": ["Conectar otro proyecto","Conectar outro projeto","Connecter un autre projet","Anderes Projekt verbinden","Ander project verbinden","別のプロジェクトを接続","连接其他项目","दूसरा प्रोजेक्ट कनेक्ट करें"],
 "Paste an API key to scan this site. <strong>No paid plan required.</strong>": ["Pegá una API key para escanear este sitio. <strong>No requiere plan de pago.</strong>","Cole uma API key para verificar este site. <strong>Não precisa de plano pago.</strong>","Collez une clé API pour scanner ce site. <strong>Aucun plan payant requis.</strong>","Füge einen API-Key ein, um diese Seite zu scannen. <strong>Kein kostenpflichtiger Plan nötig.</strong>","Plak een API-sleutel om deze site te scannen. <strong>Geen betaald abonnement nodig.</strong>","このサイトをスキャンするにはAPIキーを貼り付けてください。<strong>有料プラン不要。</strong>","粘贴 API 密钥以扫描此站点。<strong>无需付费套餐。</strong>","इस साइट को स्कैन करने के लिए API key पेस्ट करें। <strong>किसी पेड प्लान की ज़रूरत नहीं।</strong>"],
 "Free keys start with <code>vs_pk_anon_</code> (temporary). Account keys start with <code>vs_pk_</code>.": ["Las keys gratis empiezan con <code>vs_pk_anon_</code> (temporales). Las de cuenta empiezan con <code>vs_pk_</code>.","As chaves grátis começam com <code>vs_pk_anon_</code> (temporárias). As de conta começam com <code>vs_pk_</code>.","Les clés gratuites commencent par <code>vs_pk_anon_</code> (temporaires). Les clés de compte par <code>vs_pk_</code>.","Kostenlose Keys beginnen mit <code>vs_pk_anon_</code> (temporär). Konto-Keys mit <code>vs_pk_</code>.","Gratis sleutels beginnen met <code>vs_pk_anon_</code> (tijdelijk). Account-sleutels met <code>vs_pk_</code>.","無料キーは <code>vs_pk_anon_</code>（一時的）、アカウントキーは <code>vs_pk_</code> で始まります。","免费密钥以 <code>vs_pk_anon_</code> 开头（临时）。账户密钥以 <code>vs_pk_</code> 开头。","मुफ़्त keys <code>vs_pk_anon_</code> से शुरू होती हैं (अस्थायी)। खाता keys <code>vs_pk_</code> से।"],
 "Sync triggered — check your NextGuard dashboard in a few seconds.": ["Sincronización disparada — revisá tu dashboard NextGuard en unos segundos.","Sincronização disparada — confira seu painel NextGuard em alguns segundos.","Synchronisation lancée — vérifiez votre tableau de bord NextGuard dans quelques secondes.","Sync ausgelöst — prüfe dein NextGuard-Dashboard in ein paar Sekunden.","Sync gestart — controleer je NextGuard-dashboard over enkele seconden.","同期を実行 — 数秒後にNextGuardダッシュボードを確認してください。","已触发同步 — 几秒后查看你的 NextGuard 仪表板。","सिंक शुरू — कुछ सेकंड में अपना NextGuard डैशबोर्ड देखें।"],
 "Connected. Syncing your site… check the scan on the page where you got this key.": ["Conectado. Sincronizando tu sitio… revisá el escaneo en la página donde obtuviste esta key.","Conectado. Sincronizando seu site… confira a verificação na página onde obteve esta chave.","Connecté. Synchronisation de votre site… vérifiez le scan sur la page où vous avez obtenu cette clé.","Verbunden. Synchronisiere deine Seite… prüfe den Scan auf der Seite, wo du den Key bekommen hast.","Verbonden. Je site wordt gesynchroniseerd… bekijk de scan op de pagina waar je deze sleutel kreeg.","接続しました。サイトを同期中… キーを取得したページでスキャンを確認してください。","已连接。正在同步你的站点… 在获取此密钥的页面查看扫描结果。","कनेक्ट हो गया। आपकी साइट सिंक हो रही है… जहाँ से key ली वहाँ स्कैन देखें।"],
 "<strong>Free, no account:</strong> open <a href=\"%s/#scan\" target=\"_blank\">nextguardhq.com → Free scan</a>, run the free CMS scan and copy the key it gives you — it works for a few scans, no sign-up.": ["<strong>Gratis, sin cuenta:</strong> abrí <a href=\"%s/#scan\" target=\"_blank\">nextguardhq.com → Escaneo gratis</a>, corré el escaneo CMS gratis y copiá la key que te da — sirve para unos escaneos, sin registrarte.","<strong>Grátis, sem conta:</strong> abra <a href=\"%s/#scan\" target=\"_blank\">nextguardhq.com → Verificação grátis</a>, rode a verificação CMS grátis e copie a chave — serve para algumas verificações, sem cadastro.","<strong>Gratuit, sans compte :</strong> ouvrez <a href=\"%s/#scan\" target=\"_blank\">nextguardhq.com → Scan gratuit</a>, lancez le scan CMS gratuit et copiez la clé — valable pour quelques scans, sans inscription.","<strong>Kostenlos, kein Konto:</strong> öffne <a href=\"%s/#scan\" target=\"_blank\">nextguardhq.com → Kostenloser Scan</a>, führe den kostenlosen CMS-Scan aus und kopiere den Key — gilt für einige Scans, ohne Anmeldung.","<strong>Gratis, geen account:</strong> open <a href=\"%s/#scan\" target=\"_blank\">nextguardhq.com → Gratis scan</a>, voer de gratis CMS-scan uit en kopieer de sleutel — werkt voor enkele scans, zonder aanmelden.","<strong>無料・アカウント不要:</strong> <a href=\"%s/#scan\" target=\"_blank\">nextguardhq.com → 無料スキャン</a> を開き、無料CMSスキャンを実行してキーをコピー — 数回分、登録不要。","<strong>免费，无需账户：</strong>打开 <a href=\"%s/#scan\" target=\"_blank\">nextguardhq.com → 免费扫描</a>，运行免费 CMS 扫描并复制密钥 — 可用几次，无需注册。","<strong>मुफ़्त, बिना खाता:</strong> <a href=\"%s/#scan\" target=\"_blank\">nextguardhq.com → मुफ़्त स्कैन</a> खोलें, मुफ़्त CMS स्कैन चलाएं और मिली key कॉपी करें — कुछ स्कैन के लिए, बिना साइन-अप।"],
 "<strong>With a NextGuard account:</strong> paste your key from <a href=\"%s/account\" target=\"_blank\">Account → API Keys</a> to link this site to a project for continuous monitoring.": ["<strong>Con cuenta NextGuard:</strong> pegá tu key de <a href=\"%s/account\" target=\"_blank\">Cuenta → API Keys</a> para vincular este sitio a un proyecto con monitoreo continuo.","<strong>Com conta NextGuard:</strong> cole sua chave de <a href=\"%s/account\" target=\"_blank\">Conta → API Keys</a> para vincular este site a um projeto com monitoramento contínuo.","<strong>Avec un compte NextGuard :</strong> collez votre clé depuis <a href=\"%s/account\" target=\"_blank\">Compte → Clés API</a> pour lier ce site à un projet avec surveillance continue.","<strong>Mit NextGuard-Konto:</strong> füge deinen Key aus <a href=\"%s/account\" target=\"_blank\">Konto → API-Keys</a> ein, um diese Seite mit einem Projekt für laufende Überwachung zu verknüpfen.","<strong>Met een NextGuard-account:</strong> plak je sleutel uit <a href=\"%s/account\" target=\"_blank\">Account → API-sleutels</a> om deze site aan een project te koppelen voor doorlopende monitoring.","<strong>NextGuardアカウントあり:</strong> <a href=\"%s/account\" target=\"_blank\">アカウント → APIキー</a> のキーを貼り付けて、このサイトを継続モニタリングのプロジェクトに紐付けます。","<strong>拥有 NextGuard 账户：</strong>从 <a href=\"%s/account\" target=\"_blank\">账户 → API 密钥</a> 粘贴你的密钥，将此站点关联到项目以持续监控。","<strong>NextGuard खाते के साथ:</strong> <a href=\"%s/account\" target=\"_blank\">खाता → API Keys</a> से अपनी key पेस्ट करें ताकि यह साइट निरंतर निगरानी के लिए एक प्रोजेक्ट से जुड़े।"],
 "Have a paid NextGuard account? You can connect it with your API key using the device-authorization flow below — that links this site to a project for ongoing monitoring.": ["¿Tenés una cuenta NextGuard de pago? Conectala con tu API key usando el flujo de device-auth de abajo — vincula este sitio a un proyecto con monitoreo continuo.","Tem uma conta NextGuard paga? Conecte com sua API key usando o fluxo de device-auth abaixo — vincula este site a um projeto com monitoramento contínuo.","Vous avez un compte NextGuard payant ? Connectez-le avec votre clé API via le flux d'autorisation ci-dessous — il lie ce site à un projet pour une surveillance continue.","Hast du ein kostenpflichtiges NextGuard-Konto? Verbinde es mit deinem API-Key über den Device-Auth-Flow unten — das verknüpft diese Seite mit einem Projekt für laufende Überwachung.","Heb je een betaald NextGuard-account? Verbind het met je API-sleutel via de device-auth-flow hieronder — dit koppelt deze site aan een project voor doorlopende monitoring.","有料のNextGuardアカウントをお持ちですか？下のデバイス認証フローでAPIキーを使って接続すると、このサイトが継続モニタリングのプロジェクトに紐付きます。","拥有付费 NextGuard 账户？可使用下方的设备授权流程通过 API 密钥连接 — 将此站点关联到项目以持续监控。","पेड NextGuard खाता है? नीचे device-auth फ्लो से अपनी API key द्वारा कनेक्ट करें — यह साइट को निरंतर निगरानी के प्रोजेक्ट से जोड़ता है।"],
 "Automatically syncs your installed plugins and themes to <a href=\"%s\" target=\"_blank\">NextGuard</a> for continuous CVE monitoring.": ["Sincroniza automáticamente tus plugins y temas instalados con <a href=\"%s\" target=\"_blank\">NextGuard</a> para monitoreo continuo de CVEs.","Sincroniza automaticamente seus plugins e temas instalados com <a href=\"%s\" target=\"_blank\">NextGuard</a> para monitoramento contínuo de CVEs.","Synchronise automatiquement vos plugins et thèmes installés avec <a href=\"%s\" target=\"_blank\">NextGuard</a> pour une surveillance CVE continue.","Synchronisiert deine installierten Plugins und Themes automatisch mit <a href=\"%s\" target=\"_blank\">NextGuard</a> für laufende CVE-Überwachung.","Synchroniseert automatisch je geïnstalleerde plugins en thema's met <a href=\"%s\" target=\"_blank\">NextGuard</a> voor doorlopende CVE-monitoring.","インストール済みのプラグインとテーマを <a href=\"%s\" target=\"_blank\">NextGuard</a> に自動同期し、CVEを継続監視します。","自动将你已安装的插件和主题同步到 <a href=\"%s\" target=\"_blank\">NextGuard</a> 进行持续 CVE 监控。","आपके इंस्टॉल किए प्लगइन और थीम को निरंतर CVE निगरानी के लिए <a href=\"%s\" target=\"_blank\">NextGuard</a> से अपने आप सिंक करता है।"],
 "<strong>NextGuard:</strong> Your site is using a legacy API key configuration. Please reconnect below using the new Device Authorization Flow.": ["<strong>NextGuard:</strong> tu sitio usa una configuración antigua de API key. Reconectá abajo con el nuevo Device Authorization Flow.","<strong>NextGuard:</strong> seu site usa uma configuração antiga de API key. Reconecte abaixo com o novo Device Authorization Flow.","<strong>NextGuard :</strong> votre site utilise une ancienne configuration de clé API. Reconnectez-vous ci-dessous avec le nouveau Device Authorization Flow.","<strong>NextGuard:</strong> Deine Seite nutzt eine alte API-Key-Konfiguration. Verbinde unten mit dem neuen Device Authorization Flow neu.","<strong>NextGuard:</strong> je site gebruikt een verouderde API-sleutelconfiguratie. Verbind hieronder opnieuw met de nieuwe Device Authorization Flow.","<strong>NextGuard:</strong> サイトは旧APIキー設定を使用しています。下の新しいデバイス認証フローで再接続してください。","<strong>NextGuard：</strong>你的站点使用旧的 API 密钥配置。请使用下方新的设备授权流程重新连接。","<strong>NextGuard:</strong> आपकी साइट पुरानी API key कॉन्फ़िगरेशन उपयोग कर रही है। नीचे नए Device Authorization Flow से फिर कनेक्ट करें।"],
 "Go to <a href=\"%s/account\" target=\"_blank\">nextguardhq.com/account → Connected Devices</a> and enter this code:": ["Andá a <a href=\"%s/account\" target=\"_blank\">nextguardhq.com/account → Connected Devices</a> e ingresá este código:","Vá em <a href=\"%s/account\" target=\"_blank\">nextguardhq.com/account → Connected Devices</a> e insira este código:","Allez sur <a href=\"%s/account\" target=\"_blank\">nextguardhq.com/account → Connected Devices</a> et entrez ce code :","Gehe zu <a href=\"%s/account\" target=\"_blank\">nextguardhq.com/account → Connected Devices</a> und gib diesen Code ein:","Ga naar <a href=\"%s/account\" target=\"_blank\">nextguardhq.com/account → Connected Devices</a> en voer deze code in:","<a href=\"%s/account\" target=\"_blank\">nextguardhq.com/account → Connected Devices</a> でこのコードを入力してください:","前往 <a href=\"%s/account\" target=\"_blank\">nextguardhq.com/account → Connected Devices</a> 并输入此代码：","<a href=\"%s/account\" target=\"_blank\">nextguardhq.com/account → Connected Devices</a> पर जाएं और यह कोड डालें:"],
 "I've authorized it — Continue": ["Ya lo autoricé — Continuar","Já autorizei — Continuar","Je l'ai autorisé — Continuer","Ich habe es autorisiert — Weiter","Ik heb het geautoriseerd — Verder","承認しました — 続行","我已授权 — 继续","मैंने अधिकृत कर दिया — जारी रखें"],
 "Project: <strong>%s</strong> <span style=\"color:#6b7280;font-size:12px\">(%s)</span>": ["Proyecto: <strong>%s</strong> <span style=\"color:#6b7280;font-size:12px\">(%s)</span>","Projeto: <strong>%s</strong> <span style=\"color:#6b7280;font-size:12px\">(%s)</span>","Projet : <strong>%s</strong> <span style=\"color:#6b7280;font-size:12px\">(%s)</span>","Projekt: <strong>%s</strong> <span style=\"color:#6b7280;font-size:12px\">(%s)</span>","Project: <strong>%s</strong> <span style=\"color:#6b7280;font-size:12px\">(%s)</span>","プロジェクト: <strong>%s</strong> <span style=\"color:#6b7280;font-size:12px\">(%s)</span>","项目：<strong>%s</strong> <span style=\"color:#6b7280;font-size:12px\">(%s)</span>","प्रोजेक्ट: <strong>%s</strong> <span style=\"color:#6b7280;font-size:12px\">(%s)</span>"],
 "Last sync: <strong>%s</strong>": ["Último sync: <strong>%s</strong>","Última sincronização: <strong>%s</strong>","Dernière synchro : <strong>%s</strong>","Letzter Sync: <strong>%s</strong>","Laatste sync: <strong>%s</strong>","最終同期: <strong>%s</strong>","上次同步：<strong>%s</strong>","अंतिम सिंक: <strong>%s</strong>"],
 "Please enter your API key.": ["Ingresá tu API key.","Insira sua API key.","Veuillez saisir votre clé API.","Bitte gib deinen API-Key ein.","Voer je API-sleutel in.","APIキーを入力してください。","请输入你的 API 密钥。","अपनी API key दर्ज करें।"],
 "API key is required.": ["La API key es obligatoria.","A API key é obrigatória.","La clé API est requise.","API-Key ist erforderlich.","API-sleutel is vereist.","APIキーは必須です。","需要 API 密钥。","API key आवश्यक है।"],
 "Invalid API key. Keys must start with vs_pk_": ["API key inválida. Debe empezar con vs_pk_","API key inválida. Deve começar com vs_pk_","Clé API invalide. Elle doit commencer par vs_pk_","Ungültiger API-Key. Muss mit vs_pk_ beginnen","Ongeldige API-sleutel. Moet beginnen met vs_pk_","無効なAPIキーです。vs_pk_ で始まる必要があります","API 密钥无效。必须以 vs_pk_ 开头","अमान्य API key। vs_pk_ से शुरू होनी चाहिए"],
 "Failed to get activation code from NextGuard. Check your API key.": ["No se pudo obtener el código de activación de NextGuard. Revisá tu API key.","Falha ao obter o código de ativação do NextGuard. Verifique sua API key.","Échec de l'obtention du code d'activation NextGuard. Vérifiez votre clé API.","Aktivierungscode von NextGuard konnte nicht abgerufen werden. Prüfe deinen API-Key.","Kon geen activeringscode van NextGuard ophalen. Controleer je API-sleutel.","NextGuardから認証コードを取得できませんでした。APIキーを確認してください。","无法从 NextGuard 获取激活码。请检查你的 API 密钥。","NextGuard से सक्रियण कोड नहीं मिला। अपनी API key जांचें।"],
 "Request failed.": ["La solicitud falló.","A solicitação falhou.","La requête a échoué.","Anfrage fehlgeschlagen.","Verzoek mislukt.","リクエストに失敗しました。","请求失败。","अनुरोध विफल।"],
 "Network error. Please try again.": ["Error de red. Intentá de nuevo.","Erro de rede. Tente novamente.","Erreur réseau. Réessayez.","Netzwerkfehler. Bitte erneut versuchen.","Netwerkfout. Probeer opnieuw.","ネットワークエラー。もう一度お試しください。","网络错误。请重试。","नेटवर्क त्रुटि। फिर से कोशिश करें।"],
 "Error checking status.": ["Error al verificar el estado.","Erro ao verificar o status.","Erreur lors de la vérification du statut.","Fehler beim Prüfen des Status.","Fout bij statuscontrole.","ステータス確認エラー。","检查状态出错。","स्थिति जांचने में त्रुटि।"],
 "Code expired. Please go back and request a new one.": ["El código expiró. Volvé y pedí uno nuevo.","O código expirou. Volte e solicite um novo.","Code expiré. Revenez et demandez-en un nouveau.","Code abgelaufen. Geh zurück und fordere einen neuen an.","Code verlopen. Ga terug en vraag een nieuwe aan.","コードの期限切れです。戻って新しいコードを取得してください。","代码已过期。请返回并申请新代码。","कोड समाप्त हो गया। वापस जाकर नया मांगें।"],
 "No pending activation. Please request a new code.": ["No hay activación pendiente. Pedí un código nuevo.","Nenhuma ativação pendente. Solicite um novo código.","Aucune activation en attente. Demandez un nouveau code.","Keine ausstehende Aktivierung. Fordere einen neuen Code an.","Geen activering in behandeling. Vraag een nieuwe code aan.","保留中の認証はありません。新しいコードを取得してください。","没有待处理的激活。请申请新代码。","कोई सक्रियण लंबित नहीं। नया कोड मांगें।"],
 "Unauthorized": ["No autorizado","Não autorizado","Non autorisé","Nicht autorisiert","Niet geautoriseerd","権限がありません","未授权","अनधिकृत"],
 "Last scan: %s": ["Último escaneo: %s","Última verificação: %s","Dernier scan : %s","Letzter Scan: %s","Laatste scan: %s","最終スキャン: %s","上次扫描：%s","अंतिम स्कैन: %s"],
 "Why connect a NextGuard account?": ["¿Por qué conectar una cuenta NextGuard?","Por que conectar uma conta NextGuard?","Pourquoi connecter un compte NextGuard ?","Warum ein NextGuard-Konto verbinden?","Waarom een NextGuard-account koppelen?","NextGuardアカウントを接続する理由","为何要连接 NextGuard 账户？","NextGuard खाता क्यों कनेक्ट करें?"],
 "This free scan only shows a teaser and the key expires in 2 hours. With an account this site becomes a monitored project: the full report, automatic re-scans, and email alerts whenever a new CVE hits your plugins or themes.": ["Este escaneo gratis solo muestra un adelanto y la key expira en 2 horas. Con una cuenta este sitio se convierte en un proyecto monitoreado: el informe completo, re-escaneos automáticos y alertas por email cada vez que un nuevo CVE afecte tus plugins o temas.","Esta verificação grátis mostra apenas uma prévia e a chave expira em 2 horas. Com uma conta este site vira um projeto monitorado: o relatório completo, re-verificações automáticas e alertas por e-mail sempre que um novo CVE atingir seus plugins ou temas.","Ce scan gratuit n'affiche qu'un aperçu et la clé expire dans 2 heures. Avec un compte, ce site devient un projet surveillé : le rapport complet, des re-scans automatiques et des alertes e-mail dès qu'un nouveau CVE touche vos plugins ou thèmes.","Dieser kostenlose Scan zeigt nur eine Vorschau und der Key läuft in 2 Stunden ab. Mit einem Konto wird diese Seite zu einem überwachten Projekt: der vollständige Bericht, automatische Re-Scans und E-Mail-Benachrichtigungen, sobald ein neuer CVE deine Plugins oder Themes betrifft.","Deze gratis scan toont alleen een voorproefje en de sleutel verloopt over 2 uur. Met een account wordt deze site een gemonitord project: het volledige rapport, automatische herscans en e-mailmeldingen zodra een nieuwe CVE je plugins of thema's raakt.","この無料スキャンはプレビューのみで、キーは2時間で期限切れになります。アカウントがあれば、このサイトは監視対象のプロジェクトになります：完全なレポート、自動再スキャン、新しいCVEがプラグインやテーマに影響するたびにメールアラート。","此免费扫描仅显示预览，密钥将在 2 小时后过期。拥有账户后，此站点将成为受监控项目：完整报告、自动重新扫描，以及每当新 CVE 影响你的插件或主题时的邮件提醒。","यह मुफ़्त स्कैन केवल झलक दिखाता है और key 2 घंटे में समाप्त हो जाती है। खाते के साथ यह साइट एक निगरानी प्रोजेक्ट बन जाती है: पूरी रिपोर्ट, स्वचालित री-स्कैन, और जब भी कोई नया CVE आपके प्लगइन या थीम पर असर करे तो ईमेल अलर्ट।"],
 "Already have an account? Paste your Account key (vs_pk_…) from Account → API Keys above to link this site to an existing project.": ["¿Ya tenés cuenta? Pegá tu key de Cuenta (vs_pk_…) desde Cuenta → API Keys arriba para vincular este sitio a un proyecto existente.","Já tem conta? Cole sua chave de Conta (vs_pk_…) em Conta → API Keys acima para vincular este site a um projeto existente.","Vous avez déjà un compte ? Collez votre clé de compte (vs_pk_…) depuis Compte → Clés API ci-dessus pour lier ce site à un projet existant.","Schon ein Konto? Füge oben deinen Konto-Key (vs_pk_…) aus Konto → API-Keys ein, um diese Seite mit einem bestehenden Projekt zu verknüpfen.","Heb je al een account? Plak hierboven je account-sleutel (vs_pk_…) uit Account → API-sleutels om deze site aan een bestaand project te koppelen.","すでにアカウントをお持ちですか？上の アカウント → APIキー からアカウントキー（vs_pk_…）を貼り付けて、このサイトを既存のプロジェクトに紐付けてください。","已有账户？从上方 账户 → API 密钥 粘贴你的账户密钥（vs_pk_…），将此站点关联到现有项目。","पहले से खाता है? इस साइट को मौजूदा प्रोजेक्ट से जोड़ने के लिए ऊपर खाता → API Keys से अपनी खाता key (vs_pk_…) पेस्ट करें।"],
 "Create free account": ["Crear cuenta gratis","Criar conta grátis","Créer un compte gratuit","Kostenloses Konto erstellen","Gratis account aanmaken","無料アカウント作成","创建免费账户","मुफ़्त खाता बनाएं"],
 "Full vulnerability report (no blur)": ["Informe completo de vulnerabilidades (sin difuminar)","Relatório completo de vulnerabilidades (sem desfoque)","Rapport complet des vulnérabilités (sans flou)","Vollständiger Schwachstellenbericht (ohne Unschärfe)","Volledig kwetsbaarhedenrapport (zonder blur)","完全な脆弱性レポート（ぼかしなし）","完整漏洞报告（无模糊）","पूरी कमज़ोरी रिपोर्ट (बिना धुंधलापन)"],
 "1 monitored project": ["1 proyecto monitoreado","1 projeto monitorado","1 projet surveillé","1 überwachtes Projekt","1 gemonitord project","監視プロジェクト 1 件","1 个受监控项目","1 निगरानी प्रोजेक्ट"],
 "CVE database access": ["Acceso a la base de datos de CVEs","Acesso ao banco de dados de CVEs","Accès à la base de données CVE","Zugriff auf die CVE-Datenbank","Toegang tot CVE-database","CVEデータベースへのアクセス","CVE 数据库访问","CVE डेटाबेस एक्सेस"],
 "Get Monitoring": ["Obtener Monitoring","Obter Monitoring","Choisir Monitoring","Monitoring holen","Monitoring nemen","Monitoring を入手","获取 Monitoring","Monitoring लें"],
 "Continuous automatic re-scans": ["Re-escaneos automáticos continuos","Re-verificações automáticas contínuas","Re-scans automatiques continus","Kontinuierliche automatische Re-Scans","Doorlopende automatische herscans","継続的な自動再スキャン","持续自动重新扫描","निरंतर स्वचालित री-स्कैन"],
 "Email alerts on new CVEs": ["Alertas por email ante nuevos CVEs","Alertas por e-mail sobre novos CVEs","Alertes e-mail pour les nouveaux CVE","E-Mail-Benachrichtigungen bei neuen CVEs","E-mailmeldingen bij nieuwe CVE's","新しいCVEのメールアラート","新 CVE 邮件提醒","नए CVE पर ईमेल अलर्ट"],
 "Unlimited scans, no expiry": ["Escaneos ilimitados, sin caducidad","Verificações ilimitadas, sem expiração","Scans illimités, sans expiration","Unbegrenzte Scans, kein Ablauf","Onbeperkte scans, geen vervaldatum","無制限スキャン、期限なし","无限扫描，永不过期","असीमित स्कैन, कोई समाप्ति नहीं"],
 "Get Starter": ["Obtener Starter","Obter Starter","Choisir Starter","Starter holen","Starter nemen","Starter を入手","获取 Starter","Starter लें"],
 "Everything in Monitoring": ["Todo lo de Monitoring","Tudo do Monitoring","Tout Monitoring inclus","Alles aus Monitoring","Alles uit Monitoring","Monitoring の全機能","包含 Monitoring 全部","Monitoring का सब कुछ"],
 "Multiple projects & environments": ["Múltiples proyectos y entornos","Múltiplos projetos e ambientes","Plusieurs projets et environnements","Mehrere Projekte & Umgebungen","Meerdere projecten & omgevingen","複数のプロジェクトと環境","多个项目和环境","कई प्रोजेक्ट और एनवायरनमेंट"],
 "Scan history & auto-patching": ["Historial de escaneos y auto-parcheo","Histórico de verificações e auto-correção","Historique des scans et auto-correctifs","Scan-Verlauf & Auto-Patching","Scangeschiedenis & auto-patching","スキャン履歴と自動パッチ","扫描历史和自动修补","स्कैन इतिहास और ऑटो-पैचिंग"],
}

def po_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

here = os.path.dirname(os.path.abspath(__file__))
for loc in LOCALES:
    i = IDX[loc]
    lines = [
        'msgid ""',
        'msgstr ""',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        '"Language: %s\\n"' % loc,
        '',
    ]
    for msgid, arr in T.items():
        lines.append('msgid "%s"' % po_escape(msgid))
        lines.append('msgstr "%s"' % po_escape(arr[i]))
        lines.append('')
    with open(os.path.join(here, f"nextguard-{loc}.po"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"nextguard-{loc}.po  ({len(T)} strings)")
print("done — now convert .po -> .mo with WP's PO/MO classes (wp eval)")
